# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: customer.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0e\x63ustomer.proto\x12\x08\x63ustomer"\x83\x01\n\x15\x43reateCustomerRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12\x0c\n\x04\x63ity\x18\x04 \x01(\t\x12\x13\n\x0bpostal_code\x18\x05 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x06 \x01(\t"O\n\x16\x43reateCustomerResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x13\n\x0b\x63ustomer_id\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t2f\n\x0f\x43ustomerService\x12S\n\x0e\x43reateCustomer\x12\x1f.customer.CreateCustomerRequest\x1a .customer.CreateCustomerResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "customer_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals["_CREATECUSTOMERREQUEST"]._serialized_start = 29
    _globals["_CREATECUSTOMERREQUEST"]._serialized_end = 160
    _globals["_CREATECUSTOMERRESPONSE"]._serialized_start = 162
    _globals["_CREATECUSTOMERRESPONSE"]._serialized_end = 241
    _globals["_CUSTOMERSERVICE"]._serialized_start = 243
    _globals["_CUSTOMERSERVICE"]._serialized_end = 345
# @@protoc_insertion_point(module_scope)
