# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from grpc_client import (
    user_profile_pb2 as auth_dot_grpc__api_dot_user__profile_dot_user__profile__pb2,
)


class UserProfileServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUserProfile = channel.unary_unary(
            "/auth.UserProfileService/GetUserProfile",
            request_serializer=auth_dot_grpc__api_dot_user__profile_dot_user__profile__pb2.UserProfileRequest.SerializeToString,
            response_deserializer=auth_dot_grpc__api_dot_user__profile_dot_user__profile__pb2.UserProfileResponse.FromString,
        )


class UserProfileServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetUserProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_UserProfileServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetUserProfile": grpc.unary_unary_rpc_method_handler(
            servicer.GetUserProfile,
            request_deserializer=auth_dot_grpc__api_dot_user__profile_dot_user__profile__pb2.UserProfileRequest.FromString,
            response_serializer=auth_dot_grpc__api_dot_user__profile_dot_user__profile__pb2.UserProfileResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "auth.UserProfileService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class UserProfileService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetUserProfile(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/auth.UserProfileService/GetUserProfile",
            auth_dot_grpc__api_dot_user__profile_dot_user__profile__pb2.UserProfileRequest.SerializeToString,
            auth_dot_grpc__api_dot_user__profile_dot_user__profile__pb2.UserProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
