# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth/grpc_api/user_profile/user_profile.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-auth/grpc_api/user_profile/user_profile.proto\x12\x04\x61uth\"<\n\x12UserProfileRequest\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x10\n\x08id_token\x18\x02 \x01(\t\"<\n\nPermission\x12\x15\n\rpermission_id\x18\x01 \x01(\x05\x12\x17\n\x0fpermission_name\x18\x02 \x01(\t\"Q\n\x04Role\x12\x0f\n\x07role_id\x18\x01 \x01(\x05\x12\x11\n\trole_name\x18\x02 \x01(\t\x12%\n\x0bpermissions\x18\x03 \x03(\x0b\x32\x10.auth.Permission\"E\n\x04User\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\r\n\x05phone\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\"l\n\x13UserProfileResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x18\n\x04user\x18\x02 \x01(\x0b\x32\n.auth.User\x12\x19\n\x05roles\x18\x03 \x03(\x0b\x32\n.auth.Role\x12\x0f\n\x07message\x18\x04 \x01(\t2[\n\x12UserProfileService\x12\x45\n\x0eGetUserProfile\x12\x18.auth.UserProfileRequest\x1a\x19.auth.UserProfileResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth.grpc_api.user_profile.user_profile_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USERPROFILEREQUEST._serialized_start=55
  _USERPROFILEREQUEST._serialized_end=115
  _PERMISSION._serialized_start=117
  _PERMISSION._serialized_end=177
  _ROLE._serialized_start=179
  _ROLE._serialized_end=260
  _USER._serialized_start=262
  _USER._serialized_end=331
  _USERPROFILERESPONSE._serialized_start=333
  _USERPROFILERESPONSE._serialized_end=441
  _USERPROFILESERVICE._serialized_start=443
  _USERPROFILESERVICE._serialized_end=534
# @@protoc_insertion_point(module_scope)
