# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import grpc_api.customer_pb2 as customer__pb2


class CustomerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateCustomer = channel.unary_unary(
            "/customer.CustomerService/CreateCustomer",
            request_serializer=customer__pb2.CreateCustomerRequest.SerializeToString,
            response_deserializer=customer__pb2.CreateCustomerResponse.FromString,
        )


class CustomerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateCustomer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_CustomerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "CreateCustomer": grpc.unary_unary_rpc_method_handler(
            servicer.CreateCustomer,
            request_deserializer=customer__pb2.CreateCustomerRequest.FromString,
            response_serializer=customer__pb2.CreateCustomerResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "customer.CustomerService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class CustomerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateCustomer(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/customer.CustomerService/CreateCustomer",
            customer__pb2.CreateCustomerRequest.SerializeToString,
            customer__pb2.CreateCustomerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
