events {}

http {

    upstream auth_upstream {
        server 127.0.0.1:8001;
    }

    upstream customer_upstream {
        server 127.0.0.1:8000;
    }

    upstream product_upstream {
        server 127.0.0.1:8003;
    }

    server {
        listen 80;
        server_name _;

        # ========================
        # HEALTH CHECK
        # ========================
        location /health {
            return 200 "ok";
        }

        # ========================
        # AUTH API
        # ========================
        location /api/auth/ {

            rewrite ^/api/(.*)$ /$1 break;

            proxy_pass http://auth_upstream;
            proxy_http_version 1.1;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto http;
        }

        # ========================
        # CUSTOMER API
        # ========================
        location /api/customer/ {

            rewrite ^/api/(.*)$ /$1 break;

            proxy_pass http://customer_upstream;
            proxy_http_version 1.1;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto http;
        }

         # ========================
        # PRODUCT API
        # ========================
        location /api/product/ {

            rewrite ^/api/(.*)$ /$1 break;

            proxy_pass http://product_upstream;
            proxy_http_version 1.1;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto http;
        }
    }
}