events {}

http {
    upstream auth_upstream {
        server 127.0.0.1:8001;
    }

    upstream customer_upstream {
        server 127.0.0.1:8000;
    }

    server {
        listen 80;

        location /auth/ {
            proxy_pass http://auth_upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /customer/ {
            proxy_pass http://customer_upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        location /health {
            return 200 "ok";
        }
    }
}
