events {}

http {
    upstream auth_upstream {
        server auth:8001;
    }

    upstream customer_upstream {
        server customer:8000;
    }

    server {
        listen 80;

        location /auth/ {
            proxy_pass http://auth_upstream;
        }

        location /customer/ {
            proxy_pass http://customer_upstream;
        }
    }
}
