name: Build & Deploy

on:
  push:
    branches:
      - "**"

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
# ---------------- BUILD ----------------
  build:
    runs-on: ubuntu-latest

    outputs:
      image_tag: ${{ steps.vars.outputs.tag }}

    steps:
      - uses: actions/checkout@v4

      - name: Generate image tag
        id: vars
        run: |
          BRANCH=$(echo "${GITHUB_REF_NAME}" | tr '/' '-')
          TS=$(date +%Y%m%d%H%M%S)
          TAG="${BRANCH}-${TS}"
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Auth
        run: |
          docker build -t $DOCKERHUB_USERNAME/amcart-auth:${{ steps.vars.outputs.tag }} ./app/auth
          docker push $DOCKERHUB_USERNAME/amcart-auth:${{ steps.vars.outputs.tag }}

      - name: Build & Push Customer
        run: |
          docker build -f ./app/customer/Dockerfile.api \
            -t $DOCKERHUB_USERNAME/amcart-customer:${{ steps.vars.outputs.tag }} \
            ./app/customer
          docker push $DOCKERHUB_USERNAME/amcart-customer:${{ steps.vars.outputs.tag }}

      - name: Build & Push Nginx
        run: |
          docker build -t $DOCKERHUB_USERNAME/amcart-nginx:${{ steps.vars.outputs.tag }} ./app/nginx
          docker push $DOCKERHUB_USERNAME/amcart-nginx:${{ steps.vars.outputs.tag }}

# ---------------- DEPLOY ----------------
  deploy:
    needs: build
    runs-on: ubuntu-latest

    if: always()
    # if: |
    #   github.ref_name == 'main' ||
    #   startsWith(github.ref_name, 'release/')

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy ECS
        run: |
          aws cloudformation deploy \
            --stack-name amcart-stack \
            --template-file infra/ecs-alb-efs.yml \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides \
              VpcId=vpc-07cf0bd2defe827ee \
              Subnets=subnet-002e4892bb31ff833,subnet-019e055615dc1a073 \
              ImageTag=${{ needs.build.outputs.image_tag }}
