name: Build & Push Docker Images

on:
  push:
    branches:
      - "**"
      # - release/**
      # - main

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate image tag (branch + timestamp + sha)
        run: |
          BRANCH=$(echo "${GITHUB_REF_NAME}" | tr '/' '-' | tr '[:upper:]' '[:lower:]')
          TIMESTAMP=$(date +%Y%m%d-%H%M%S)
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
          TAG="${BRANCH}-${TIMESTAMP}-${SHORT_SHA}"
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "Using image tag: $TAG"

      - name: Save image tag
        run: echo "$TAG" > image-tag.txt

      - name: Upload image tag artifact
        uses: actions/upload-artifact@v4
        with:
          name: image-tag
          path: image-tag.txt

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Auth image
        run: |
          docker build -t $DOCKERHUB_USERNAME/amcart-auth:$TAG ./app/auth
          docker push $DOCKERHUB_USERNAME/amcart-auth:$TAG

      - name: Build & Push Customer image
        run: |
          docker build \
            -f ./app/customer/Dockerfile.api \
            -t $DOCKERHUB_USERNAME/amcart-customer:$TAG \
            ./app/customer
          docker push $DOCKERHUB_USERNAME/amcart-customer:$TAG
      
      - name: Build & Push Nginx image
        run: |
          docker build -t $DOCKERHUB_USERNAME/amcart-nginx:$TAG ./app/nginx
          docker push $DOCKERHUB_USERNAME/amcart-nginx:$TAG
