name: Deploy ECS Infra

on:
  workflow_run:
    workflows: ["Build & Push Docker Images"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download image tag artifact
        uses: actions/download-artifact@v4
        with:
          name: image-tag
          run-id: ${{ github.event.workflow_run.id }}

      - name: Read image tag
        run: |
          TAG=$(cat image-tag.txt)
          echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV
          echo "Deploying image tag: $TAG"

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy CloudFormation
        run: |
          aws cloudformation deploy \
            --stack-name amcart-stack \
            --template-file infra/ecs-alb-efs.yml \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides \
              VpcId=vpc-07cf0bd2defe827ee \
              Subnets=subnet-002e4892bb31ff833,subnet-019e055615dc1a073 \
              ImageTag=${IMAGE_TAG}
